[workspace]
members = [
    "apps/mkps4-cli",
    "apps/mkps4-gui/src-tauri",
    "crates/mkps4-core",
    "crates/mkps4-emulator-store",
]
default-members = ["apps/mkps4-cli"]
resolver = "3"

[workspace.package]
version = "0.1.0"
edition = "2024"
license = "MIT OR Apache-2.0"

[workspace.dependencies]
anyhow = "1.0"
clap = { version = "4.5", features = ["derive", "env"] }
image = { version = "0.25", default-features = false, features = ["jpeg", "png"] }
reqwest = { version = "0.13", default-features = false, features = ["blocking", "rustls"] }
tempfile = "3.27"
zip = { version = "2.4", default-features = false, features = ["deflate"] }
