[package]
name = "mkps4"
version.workspace = true
edition.workspace = true
description = "Build PS4 PS2 Classics projects from the command line"
license.workspace = true

[dependencies]
anyhow.workspace = true
clap.workspace = true
mkps4-core = { path = "../../crates/mkps4-core" }
mkps4-emulator-store = { path = "../../crates/mkps4-emulator-store" }
